// AUTO-GENERATED: do not edit by hand. Regenerated by
// `node scripts/sync-version.mjs` (or `pnpm prebuild`), which reads
// MARKETING_VERSION from `../macos/project.yml`. Keeping this as the
// only place the version is referenced in the web app prevents the
// landing page from drifting from the actual shipped DMG.
export const VERSION_NUM = "0.1.11";
export const VERSION = `v${VERSION_NUM}`;
export const DOWNLOAD_URL = `https://dl.tellhark.com/Hark-${VERSION_NUM}.dmg`;
