#!/usr/bin/env node
// Pull MARKETING_VERSION from macos/project.yml — the source of truth
// for what version the next DMG will ship as — and write it into
// web/lib/version.ts so the landing page never drifts from the app.
// Wired into web/package.json as `prebuild`, so `pnpm build` (Vercel,
// CI, local) always regenerates the constant first.
//
// Why grep-not-parse: yaml is a heavy dep for one field. The format of
// the line is stable: `    MARKETING_VERSION: "0.1.3"` (two-space indent,
// double-quoted value). If we ever introduce more parsing needs we can
// swap to `js-yaml`.

import { readFileSync, writeFileSync } from "node:fs";
import { fileURLToPath } from "node:url";
import { dirname, resolve } from "node:path";

const here = dirname(fileURLToPath(import.meta.url));
const projectYml = resolve(here, "../../macos/project.yml");
const versionFile = resolve(here, "../lib/version.ts");

const text = readFileSync(projectYml, "utf-8");
const match = text.match(/^\s*MARKETING_VERSION:\s*"([^"]+)"/m);
if (!match) {
  console.error(
    `sync-version: could not find MARKETING_VERSION in ${projectYml}`,
  );
  process.exit(1);
}
const version = match[1];

const contents = `// AUTO-GENERATED: do not edit by hand. Regenerated by
// \`node scripts/sync-version.mjs\` (or \`pnpm prebuild\`), which reads
// MARKETING_VERSION from \`../macos/project.yml\`. Keeping this as the
// only place the version is referenced in the web app prevents the
// landing page from drifting from the actual shipped DMG.
export const VERSION_NUM = "${version}";
export const VERSION = \`v\${VERSION_NUM}\`;
export const DOWNLOAD_URL = \`https://dl.tellhark.com/Hark-\${VERSION_NUM}.dmg\`;
`;

writeFileSync(versionFile, contents);
console.log(`sync-version: web/lib/version.ts → ${version}`);
